### ISSUE TITLE
Single quotes within guillemets messes up highlighting

### ISSUE THREAD

**Issue by hoelzro** [vim-perl/vim-perl#100]
Example:

```perl6

my $string = 'foobar';
«# '»

Something'
```

**Comment by hinrik** [comment]
I don't see what the issue is here (nor when the issue was created, at commit 209aedc). The comment immediately after `«` is highlighted correctly (to the end of the line only), then `Something` is highlighted as part of the string, then the single quote at the end is highlighted as the start of an embedded single-quoted string, which is allowed inside `«»`/`<<>>`.

http://design.perl6.org/S02.html#Angle_quotes_%28quote_words%29
