### ISSUE TITLE
\<void\> doesn't find 'void' due to iskeyword setting

### ISSUE THREAD

**Issue by hoelzro** [vim-perl/vim-perl#190]
If you use the search pattern `\<void\>`, a string literal containing the text "void" using single quotes will not be found by the search.  Neither will boolean adverbial pairs (ex. `:write`).  Perl 6 allows `'` and `-` in identifiers (as well as `:`, if you count fully qualified identifiers), but only in the middle of an identifier.  Unfortunately, Vim's `iskeyword` setting is not so flexible, so barring modifying Vim or the various operations that consult `iskeyword`, I don't know if this can be fixed.

**Comment by hinrik** [comment]
Considering how rare it is for people to use `'` as part of an identifier vs using it as a string delimiter, I think it makes sense to remove it from `iskeyword`.

Do you remember why you added `:` to `iskeyword` in 11049a7 ? I think it makes sense to remove that too, for the reason you mentioned (i.e. when searching for `\<write\>`).

**Comment by hoelzro** [comment]
I agree with removing `'` from `'iskeyword`.

I added `:` for feature parity with `perl.vim`.

**Comment by hinrik** [comment]
>I added `:` for feature parity with `perl.vim`.

Ah, I see. Looking at f7f84ea, it seems the colon got slipped in by accident due to a pre-existing (but commented out) `iskeyword` line containing it. That comment was introduced in 9976c33, presumably because its author was entertaining the possiblity of looking up module documentation with vim's `K` command (see e.g. http://usevim.com/2012/09/07/vim101-keywordprg/).

At the time he just copied over `perl.vim`'s definition which was (and still is) `setlocal keywordprg=perldoc\ -f`, which can only look up (Perl 5) function names and therefore has no need for `:` in `iskeyword`. But nowadays it calls `p6doc` which can look up module documentation too. So if we do remove the colon from `perl6.vim`'s `iskeyword`, the `K` command won't work on module names with colons anymore.

I still think it makes sense to follow through with the removal though, to keep the usefulness of `\<` and `\>`.

**Comment by hoelzro** [comment]
I think if `K` is the reason it's present (I use `perlhelp` for Perl 5, which uses `\ph`), then to me the wiser course of action is to remove the colon, and have perl(5|6) buffer-local mappings for `K` that Do The Right Thing™.

**Comment by hoelzro** [comment]
@hinrik Do you mind if I go ahead and remove `'`/`:` from `iskeyword`?  The fallback for users is easy enough; they just need to create a `perl6` ftplugin.

As far as Perl 5 is concerned, I think we need to tread a little more litely; maybe we need to ask the community what it wants?

**Comment by hinrik** [comment]
Sounds good to me.

**Comment by hoelzro** [comment]
Alright, I've removed them from `&iskeyword`.
