### ISSUE TITLE
perl6 highlight interpolated hash does not highlight <>

### ISSUE THREAD

**Issue by lucastheisen** [vim-perl/vim-perl#199]
In perl5, the syntax highlighting in an interpolated string containing a hash value `$hash{key}`, the `$hash{` and `}` are all highlighted.  In perl6, the hash value `%hash<key>` does not highlight the analogous `<` and `>`.  If i had any idea how to write `vimscript` i'd submit a pull request...  but alas...

**Comment by hinrik** [comment]
For me they appear highlighted:

![screenshot](http://i.imgur.com/3o2iO9U.png)

Are you running the latest version, from the vim-perl repository?

It is true that Perl 5, the curly braces in a hash subscript are highlighted in the same way as the variable name, whereas in Perl 6 the angle operators are highlighted like other operators. That was intentional.

**Comment by lucastheisen** [comment]
I just installed it today using [these instructions](https://github.com/vim-perl/vim-perl#installing-using-vim-plug), and i see this:

![capture](https://cloud.githubusercontent.com/assets/1952786/10554352/afcb9446-7430-11e5-94c8-1ca2cd667b71.PNG)

Could it just be my color scheme (elflord)?  Which are you using (looks nice)?

**Comment by hinrik** [comment]
I just tested the instructions and they worked for me.

It does look like your colorscheme is the issue. It looks to me like the colors it uses for `String` and `Operator` are very similar (magenta and dim magenta). I can see how they looked the same to you, but if you look at the `my` (`Operator` highlight group) you can see it's a bit darker than the text inside the string (`String` highlight group), and the former is actually the color being used for the `<>` characters (and also the string delimiters, `''` and `""`).

I'm using this colorscheme: https://github.com/hinrik/color-scheme-literal-tango

**Comment by lucastheisen** [comment]
You are correct, it was the {{colorscheme}}.  I installed {{literal-tango}} as linked to above, and it does show the difference, but it does not look the same as your screen capture:

![capture](https://cloud.githubusercontent.com/assets/1952786/10581446/b67c768a-7650-11e5-8fb3-57aa4b50b5bf.PNG)

**Comment by hinrik** [comment]
Yeah, because in the terminal it relies on 16-color support, so it uses whatever colors your terminal has defined. Gnome-terminal offers a Tango palette in its settings dialog, though you might have to customize the first/black color to be `#2e3436`, because for some reason it defaults to `#000000` (which is not in the [Tango palette](http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines#Color_Palette)).

Other terminal emulators also support changing the color palette: https://www.google.com/search?q=tango+terminal+color+palette.
