### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by egawata** [vim-perl/vim-perl#281]
# Description of issue

Now build by Travis CI fails. Maybe that's because the default version of Ubuntu for building has changed to Xenial recently, which doesn't support perl older than 5.22.

https://travis-ci.community/t/older-perl-version-stopped-working/4294

One of the simple solution is to specify `dist: trusty` explicitly in `.travis.yml` to use Trusty instead of Xenial. I tried it, and building succeeds.

# Screenshot of the issue:

Running build with the following `.travis.yml`:

~~~yaml
language: perl
install:
  - sudo apt-get install vim
  - cpanm --notest Test::Differences Text::VimColor IO::Pty Test::Deep Parallel::ForkManager JSON Path::Tiny Test::SharedFork Test::LongString
  - git fetch origin p5-corpus-ng:origin/p5-corpus-ng
  - vim --version
script:
  - make test
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
branches:
  except:
    - p5-corpus
~~~

![スクリーンショット 2019-08-21 7 49 34](https://user-images.githubusercontent.com/299936/63390036-9d46c280-c3e8-11e9-9035-d8af99566bf9.png)

Tests with perl older than 5.22 fails.

**Comment by hoelzro** [comment]
Thanks @egawata! I've made the change you recommended to `.travis.yml` and everything is working again.

**Comment by petdance** [comment]
How are trusty and xenial different?  Why does trusty work but xenial doesn't?

**Comment by hoelzro** [comment]
@petdance From my reading of https://docs.travis-ci.com/user/reference/xenial#perl-support, Travis no longer supports perl pre-5.22 on Xenial - my guess would be due to some wonkiness that needs to be patched out to build those earlier perls.  That or they just don't want to deal with them.  I'm guessing we _could_ support earlier perls with Xenial by building perl ourselves, but we wouldn't be able to make use of Travis' Perl support for it, which would bump up build times and require us to maintain that build process.
