### ISSUE TITLE
ftplugin/perl.vim system calls 'shellxquote' logic too specific

### ISSUE THREAD

**Issue by ghost** [vim-perl/vim-perl#45]
ftplugin/perl.vim uses
    if &shellxquote != '"'
        let perlpath = system('perl -e "print join(q/,/,@INC)"')
    else
        let perlpath = system("perl -e 'print join(q/,/,@INC)'")
    endif

This fails if shellxquote is empty and the shell doesn't use double quotes. E.g. my current settings:

```
set shell=/usr/bin/rc
set shellcmdflag=-c\ eval\ $*
set shellxquote=
```

The second branch with single quotes around the print statement would work just fine for my case but it won't get chosen because my shellxquote is empty.

I understand rc may be too non-standard to accommodate. Still it took me some time to track down why loading .pl files suddenly failed with E484's. Maybe it could fail a little more gracefully.

**Comment by oliwer** [comment]
Hi. Another rc shell user here :)

I have been bitten by the same bug. But from what I understand the problem is not that "the check is not strict enough", it's that the check is inverted. Simply replacing `if &shellxquote != '"'` by `if &shellxquote == '"'` solves the problem, and makes a lot more sense!

```vim
if &shellxquote == '"'
    let perlpath = system('perl -e "print join(q/,/,@INC)"')
else
    let perlpath = system("perl -e 'print join(q/,/,@INC)'")
endif
```

This will work even if `shellxquote` is not set.

On a Windows system using cmd.exe (which requires double-quotes), the current code would fail.

**Comment by oliwer** [comment]
Posting the full error to make this bug more easily discoverable:

```
Error detected while processing BufRead Autocommands for "*.pl"
..function dist#ft#FTpl[10]..FileType Autocommands for "*"
..function <SNR>15_LoadFTPlugin[18]
..script /usr/share/vim/vim90/ftplugin/perl.vim[67]
..BufRead Autocommands for "*.pl"
..function dist#ft#FTpl[10]
..FileType Autocommands for "*"
..function <SNR>15_LoadFTPlugin[18]
..script /usr/share/vim/vim90/ftplugin/perl.vim:
line   60:
E282: Cannot read from "/tmp/vYZfoYP/0"
```

**Comment by oliwer** [comment]
@petdance @dkearns just making sure you've seen this. I can open a PR if you'e ok with the change.

**Comment by petdance** [comment]
Sure, make a PR. Thanks.
